name: mds_home
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.0  # Add CSV support
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.0.5 # For state management
  shared_preferences: ^2.2.2 # For saving theme preference
  js: ^0.6.7
  path_provider: ^2.0.15
  share_plus: ^6.0.0
  url_launcher: ^6.1.10
  universal_html: ^2.2.2
  image: ^4.0.15  # for image processing


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/2024/available_players.csv
    - assets/2024/draft_order.csv
    - assets/2024/team_needs.csv
    - assets/2025/available_players.csv
    - assets/2025/draft_order.csv
    - assets/2025/team_needs.csv
    - assets/2025/player_descriptions.csv


