name: mds_home
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.0  # Add CSV support
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.0.3 # For state management
  shared_preferences: ^2.2.2 # For saving theme preference


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/draft_order.csv
    - assets/available_players.csv
    - assets/team_needs.csv
    - assets/draft_value_chart.csv

