name: mds_home
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2 # For saving theme preference
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.0  # Add animations
  js: ^0.7.1
  path_provider: ^2.0.15
  share_plus: ^11.0.0
  url_launcher: ^6.1.10
  universal_html: ^2.2.2
  image: ^4.0.15  # for image processing
  firebase_core: ^3.15.2
  firebase_analytics: ^11.6.0
  cloud_firestore: ^5.6.12
  image_gallery_saver: ^2.0.3
  cloud_functions: ^5.6.2  # Add this line
  cached_network_image: ^3.3.0
  flutter_markdown: ^0.7.7+1
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.20.2
  fl_chart: ^0.71.0
  file_picker: ^10.2.0
  data_table_2: ^2.5.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # Core images
    - data/images/
    - data/images/ff/
    - data/images/gm/
    - data/images/blog/
    - data/images/data/
    
    # Draft simulation data by year
    - data/processed/draft_sim/
    - data/processed/draft_sim/2024/
    - data/processed/draft_sim/2025/
    - data/processed/draft_sim/2026/
    
    # Player statistics and rankings
    - data/processed/player_stats/
    - data/processed/rankings/
    - data/processed/team_data/
    - data/processed/team_data/current_players_combined.csv
    - data/processed/projections/
    
    # ADP data (keeping original path for now)
    - data_processing/assets/data/adp/

