// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLO_VAZ9l6PK541-tFkYRquISv5x1I-Dw',
    appId: '1:900728713837:web:3e0c47b05b144c758f8564',
    messagingSenderId: '900728713837',
    projectId: 'nfl-draft-simulator-9265f',
    authDomain: 'nfl-draft-simulator-9265f.firebaseapp.com',
    databaseURL:
        'https://nfl-draft-simulator-9265f-default-rtdb.firebaseio.com',
    storageBucket: 'nfl-draft-simulator-9265f.firebasestorage.app',
    measurementId: 'G-8QGNSTTZGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy4UWWODN0984SR5CmNrN--pHgVe0Z9o0',
    appId: '1:900728713837:android:3ceb03e23fb32d4b8f8564',
    messagingSenderId: '900728713837',
    projectId: 'nfl-draft-simulator-9265f',
    databaseURL:
        'https://nfl-draft-simulator-9265f-default-rtdb.firebaseio.com',
    storageBucket: 'nfl-draft-simulator-9265f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpBjald9KzDlEylfJvCLhFSe5F6jr30Y',
    appId: '1:900728713837:ios:ed71e175b5da538f8f8564',
    messagingSenderId: '900728713837',
    projectId: 'nfl-draft-simulator-9265f',
    databaseURL:
        'https://nfl-draft-simulator-9265f-default-rtdb.firebaseio.com',
    storageBucket: 'nfl-draft-simulator-9265f.firebasestorage.app',
    iosBundleId: 'com.example.mdsHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpBjald9KzDlEylfJvCLhFSe5F6jr30Y',
    appId: '1:900728713837:ios:ed71e175b5da538f8f8564',
    messagingSenderId: '900728713837',
    projectId: 'nfl-draft-simulator-9265f',
    databaseURL:
        'https://nfl-draft-simulator-9265f-default-rtdb.firebaseio.com',
    storageBucket: 'nfl-draft-simulator-9265f.firebasestorage.app',
    iosBundleId: 'com.example.mdsHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLO_VAZ9l6PK541-tFkYRquISv5x1I-Dw',
    appId: '1:900728713837:web:787dbb2bceca4c808f8564',
    messagingSenderId: '900728713837',
    projectId: 'nfl-draft-simulator-9265f',
    authDomain: 'nfl-draft-simulator-9265f.firebaseapp.com',
    databaseURL:
        'https://nfl-draft-simulator-9265f-default-rtdb.firebaseio.com',
    storageBucket: 'nfl-draft-simulator-9265f.firebasestorage.app',
    measurementId: 'G-D1BV344KC9',
  );
}
